# --- !Ups

CREATE TABLE Products 
(
	"prodId" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	"tytul" VARCHAR  NOT NULL,
	"opis" TEXT NOT NULL,
	"catId" INTEGER NOT NULL
);

CREATE TABLE Categories 
(
	"catId" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	"tytul" VARCHAR  NOT NULL,
	"opis" TEXT NOT NULL
);

# --- !Downs

DROP TABLE Products;
DROP TABLE Categories;